// Generated by lish/tools/gen.zig from src/token.zig.
// DO NOT EDIT. Run `zig build gen` to regenerate.

module.exports = {
    // Structural source characters.
    EXPRESSION_SINGLE:         '$',
    SCOPE_THUNK:               ':',
    EXPRESSION_OPEN:           '(',
    EXPRESSION_CLOSE:          ')',
    LIST_OPEN:                 '[',
    LIST_CLOSE:                ']',
    BLOCK_OPEN:                '{',
    BLOCK_CLOSE:               '}',
    QUOTE_DOUBLE:              '"',
    QUOTE_SINGLE:              "'",
    MACRO_SEPARATOR:           '|',
    DEFERRED:                  '~',
    MACRO_BREAK:               ';',
    DECIMAL_POINT:             '.',
    NEGATIVE_SIGN:             '-',
    COMMENT:                   '#',
    BACKSLASH:                 '\\',

    // Parse-time limits.
    TERM_MAX_LENGTH:           256,
    STRING_LITERAL_MAX_LENGTH: 32768,
    MAX_EXPRESSION_NESTING:    256,
    MAX_PARAMETER_COUNT:       2048,
};
