// Generated by lish/tools/gen.zig from src/token.zig.
// DO NOT EDIT. Run `zig build gen` to regenerate.

#ifndef LISH_TREE_SITTER_CONSTANTS_H
#define LISH_TREE_SITTER_CONSTANTS_H

// Structural source characters.
#define LISH_EXPRESSION_SINGLE         '$'
#define LISH_SCOPE_THUNK               ':'
#define LISH_EXPRESSION_OPEN           '('
#define LISH_EXPRESSION_CLOSE          ')'
#define LISH_LIST_OPEN                 '['
#define LISH_LIST_CLOSE                ']'
#define LISH_BLOCK_OPEN                '{'
#define LISH_BLOCK_CLOSE               '}'
#define LISH_QUOTE_DOUBLE              '"'
#define LISH_QUOTE_SINGLE              '\''
#define LISH_MACRO_SEPARATOR           '|'
#define LISH_DEFERRED                  '~'
#define LISH_MACRO_BREAK               ';'
#define LISH_DECIMAL_POINT             '.'
#define LISH_NEGATIVE_SIGN             '-'
#define LISH_COMMENT                   '#'
#define LISH_BACKSLASH                 '\\'

// Parse-time limits.
#define LISH_TERM_MAX_LENGTH           256
#define LISH_STRING_LITERAL_MAX_LENGTH 32768
#define LISH_MAX_EXPRESSION_NESTING    256
#define LISH_MAX_PARAMETER_COUNT       2048

#endif
