// Generated by lish-zig/tools/gen.zig from src/token.zig.
// DO NOT EDIT. Run `zig build gen` to regenerate.

module.exports = {
    // Single-char escape symbols recognized after a backslash in a lish
    // string literal (the `\X` forms). Probed from token.zig's escSymToChar.
    SINGLE_CHAR_ESCAPES: ["\"", "'", "0", "\\", "a", "b", "e", "f", "n", "r", "t", "v"],
};
